### ISSUE TITLE
Fatal Crash when viewing Members List

### ISSUE THREAD

**Issue by Ao1Pointblank** [dimdenGD/LastFMRichPresence#18]
- Disabled all plugins except LastFMRichPresence v1.0.8
- used the following lastfm plugin settings:
```json
        "disableWhenSpotify": false,
        "listeningTo": true,
        "artistActivityName": false,
        "lastfmButton": false,
        "youtubeButton": false,
        "assetIcon": true,
        "artistBeforeAlbum": true,
        "disableWhenActivity": false,
        "lastFMKey": "redacted",
        "lastFMNickname": "redacted",
        "userPlatform": "youtube"
```
- toggle the server members list open (this happens on servers with and without the new activities tab at the top of the list)
- wait for lastfm plugin to refresh (~10 sec)
- observe fatal crash

I have tried enabling the BDFDB plugin in addition to LastFMRichPresence, but no change. 
the errors from console:
```
web.cf975c06a65832e459b4.js:12 [BDFDB] (v3.7.9) Fatal Error: "before" callback of Z in MemberListItem TypeError: Cannot read properties of undefined (reading 'channel')
T.t.<computed> @ web.cf975c06a65832e459b4.js:12
(anonymous) @ sentry.e7a4f258477a837f607a.js:14
Internal.console @ 0BDFDB.plugin.js:245
BDFDB.LogUtils.error @ 0BDFDB.plugin.js:254
eval @ 0BDFDB.plugin.js:303
eval @ 0BDFDB.plugin.js:2357
(anonymous) @ renderer.js:5
W @ web.cf975c06a65832e459b4.js:12
(anonymous) @ web.cf975c06a65832e459b4.js:12
a8 @ web.cf975c06a65832e459b4.js:12
oU @ web.cf975c06a65832e459b4.js:12
oG @ web.cf975c06a65832e459b4.js:12
ov @ web.cf975c06a65832e459b4.js:12
oL @ web.cf975c06a65832e459b4.js:12
r5 @ web.cf975c06a65832e459b4.js:12
ob @ web.cf975c06a65832e459b4.js:12
t.flushSync @ web.cf975c06a65832e459b4.js:12
(anonymous) @ web.cf975c06a65832e459b4.js:12
(anonymous) @ web.cf975c06a65832e459b4.js:12
(anonymous) @ web.cf975c06a65832e459b4.js:12
(anonymous) @ web.cf975c06a65832e459b4.js:12
(anonymous) @ web.cf975c06a65832e459b4.js:12
ob @ web.cf975c06a65832e459b4.js:12
t.flushSync @ web.cf975c06a65832e459b4.js:12
(anonymous) @ web.cf975c06a65832e459b4.js:12
(anonymous) @ web.cf975c06a65832e459b4.js:12
(anonymous) @ web.cf975c06a65832e459b4.js:12
```
```
web.cf975c06a65832e459b4.js:12 TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at U (web.cf975c06a65832e459b4.js:12:7266316)
    at w (web.cf975c06a65832e459b4.js:12:7266489)
    at eh (web.cf975c06a65832e459b4.js:12:7272734)
    at web.cf975c06a65832e459b4.js:12:7252769
    at Object.useMemo (web.cf975c06a65832e459b4.js:12:996931)
    at t.useMemo (web.cf975c06a65832e459b4.js:12:1108820)
    at q (web.cf975c06a65832e459b4.js:12:7252749)
    at t.Z (web.cf975c06a65832e459b4.js:12:2380258)
    at renderer.js:5:22880
    at aA (web.cf975c06a65832e459b4.js:12:990621)
    at l (web.cf975c06a65832e459b4.js:12:1045857)
    at ok (web.cf975c06a65832e459b4.js:12:1028852)
    at web.cf975c06a65832e459b4.js:12:1028718
    at oG (web.cf975c06a65832e459b4.js:12:1028726)
    at ov (web.cf975c06a65832e459b4.js:12:1025477)
    at oL (web.cf975c06a65832e459b4.js:12:1025866)
    at r5 (web.cf975c06a65832e459b4.js:12:974485)
    at ob (web.cf975c06a65832e459b4.js:12:1026315)
    at t.flushSync (web.cf975c06a65832e459b4.js:12:1057437)
    at web.cf975c06a65832e459b4.js:12:9488878
    at web.cf975c06a65832e459b4.js:12:9491222
    at web.cf975c06a65832e459b4.js:12:2513369
    at web.cf975c06a65832e459b4.js:12:2513405
    at web.cf975c06a65832e459b4.js:12:9490578
    at ob (web.cf975c06a65832e459b4.js:12:1026267)
    at t.flushSync (web.cf975c06a65832e459b4.js:12:1057437)
    at web.cf975c06a65832e459b4.js:12:9490572
    at web.cf975c06a65832e459b4.js:12:2512046
    at Array.forEach (<anonymous>)
    at ResizeObserver.<anonymous> (web.cf975c06a65832e459b4.js:12:2511979)
```

**Comment by JonJaded** [comment]
Running into this problem as well.
