### ISSUE TITLE
[CRASH] No youtube link found at Requests.getTrackYoutubeUrl - Causes "Well This Is Awkward"-Screen

### ISSUE THREAD

**Issue by Riddim-GLiTCH** [dimdenGD/LastFMRichPresence#20]
The plugin causes a crash when no YouTube link is found:
```log
Error: No youtube link found
    at Requests.getTrackYoutubeUrl (LastFMRichPresence.plugin.js:254:17)
    at async LastFMRichPresence.getLastFmData (LastFMRichPresence.plugin.js:452:28)
    at async LastFMRichPresence.updateData (LastFMRichPresence.plugin.js:432:9)
(anonymous) @ sentry.b335bd3f88b95adf113a.js:14
getTrackYoutubeUrl @ LastFMRichPresence.plugin.js:258
await in getTrackYoutubeUrl
processTicksAndRejections @ VM30142 task_queues:95
await in processTicksAndRejections
getLastFmData @ LastFMRichPresence.plugin.js:452
await in getLastFmData
updateData @ LastFMRichPresence.plugin.js:432
eval @ LastFMRichPresence.plugin.js:381
i @ sentry.b335bd3f88b95adf113a.js:1
```
Also see this attached video for when the crash happens. 

https://github.com/user-attachments/assets/3ea49458-7d53-444f-ab3e-0219d86ed8af

Other additional but potentially useful info info includes:

```md
## Discord Info
Discord Build: canary 355421 (cc1b984)
Host Version: 1.0.895 x64 (56390)
Build Override: N/A

## BetterDiscord
stable 1.11.0

## Operating System
Windows Version: 11 64-bit (10.0.26100)
```

**Comment by dezgasting** [comment]
Still relevant to this day
